; Core features
admin_chat
admin_cmd
admin_system
admin_menu
admin_hud
admin_punish
admin_rcon
gag_system
utils

; Add-ons
mapchanger
timeleft
nextmap ;Have some bugs
lambda_stats ;Not fully restored
help
cheat
anti_duckroll